@startuml
actor User
UserOrJenkins -> Maven_SurefirePlugin: TriggersExecution
UserOrJenkins -> Maven_cucumberPlugin: Set up report generation
Maven_SurefirePlugin -> TestRunner.java: LooksForFileWithNameTest
TestRunner.java -> TestListener.java: Set up listener to log execution status for debugging
TestRunner.java -> hooks.java: @Before and @After Methods setup
hooks.java ->TestContext.java: Initilaze test context
hooks.java ->BaseSteps.java: Initilaze base step and set the context
hooks.java ->BeforeAfterMethod: Set up logs to attach to report
TestRunner.java -> FeatureFile: trigger test execution
FeatureFile -> StepDefinition: LInk to step definition
@enduml
